repaired
funkwerk/jenkins-workflow pull request #9
Opened 2017-01-13 12:00 UTC by lindt

now the closure gets initialized correct

2017-01-16 08:32 UTC, Andy-FW approved these changes

2017-01-16 15:05 UTC, gfiedler requested changes
Doesn't work for me because of http://stackoverflow.com/a/28062907

2017-01-16 20:45 UTC, lindt commented
Should we wait until all Jenkins issues are fixed?
This PR repairs our broken closure handling and works for some jenkins version. That it is currently broken again in master isn't something this PR could be taken responsible for.

2017-02-15 01:22 UTC, lindt commented
timeout

2017-02-15 01:22 UTC, merged